# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "inference.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\x10image_classifier"7\n\rMSImageSample\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x11\n\tsample_id\x18\x02 \x01(\t"I\n\x15\x42\x61tchInferenceRequest\x12\x30\n\x07samples\x18\x01 \x03(\x0b\x32\x1f.image_classifier.MSImageSample"K\n\x10PredictionResult\x12\x11\n\tsample_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02"Q\n\x16\x42\x61tchInferenceResponse\x12\x37\n\x0bpredictions\x18\x01 \x03(\x0b\x32".image_classifier.PredictionResult2v\n\x11MSImageClassifier\x12\x61\n\x0cPredictBatch\x12\'.image_classifier.BatchInferenceRequest\x1a(.image_classifier.BatchInferenceResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MSIMAGESAMPLE"]._serialized_start = 37
    _globals["_MSIMAGESAMPLE"]._serialized_end = 92
    _globals["_BATCHINFERENCEREQUEST"]._serialized_start = 94
    _globals["_BATCHINFERENCEREQUEST"]._serialized_end = 167
    _globals["_PREDICTIONRESULT"]._serialized_start = 169
    _globals["_PREDICTIONRESULT"]._serialized_end = 244
    _globals["_BATCHINFERENCERESPONSE"]._serialized_start = 246
    _globals["_BATCHINFERENCERESPONSE"]._serialized_end = 327
    _globals["_MSIMAGECLASSIFIER"]._serialized_start = 329
    _globals["_MSIMAGECLASSIFIER"]._serialized_end = 447
# @@protoc_insertion_point(module_scope)
