# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MSImageClassifierStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictBatch = channel.unary_unary(
            "/image_classifier.MSImageClassifier/PredictBatch",
            request_serializer=inference__pb2.BatchInferenceRequest.SerializeToString,
            response_deserializer=inference__pb2.BatchInferenceResponse.FromString,
            _registered_method=True,
        )


class MSImageClassifierServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictBatch(self, request, context):
        """Accepts a batch of images and returns a batch of classifications"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MSImageClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PredictBatch": grpc.unary_unary_rpc_method_handler(
            servicer.PredictBatch,
            request_deserializer=inference__pb2.BatchInferenceRequest.FromString,
            response_serializer=inference__pb2.BatchInferenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "image_classifier.MSImageClassifier", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "image_classifier.MSImageClassifier", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MSImageClassifier:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/image_classifier.MSImageClassifier/PredictBatch",
            inference__pb2.BatchInferenceRequest.SerializeToString,
            inference__pb2.BatchInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
