[project]
name = "ml-msi-eurosat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev-grpc-serve = [
    "grpcio==1.83.1",
    "grpcio-tools==1.83.1",
    "matplotlib==3.11.1",
    "numpy==2.5.2",
    "pandas==2.3.3",
    "pykan==0.2.8",
    "pyyaml==6.0.3",
    "scikit-learn==1.9.0",
    "tifffile==2026.9.9",
    "torch==2.14.0",
    "torchvision==0.29.0",
    "tqdm==4.70.0",
]
dev-ray-torch = [
    "huggingface-hub==1.30.0",
    "pyarrow==25.0.1",
    "ray[train]==2.58.0",
]
dev-torch = [
    "matplotlib==3.11.1",
    "mlflow==3.15.2",
    "numpy==2.5.2",
    "pykan==0.2.8",
    "rasterio==1.5.1",
    "scikit-learn==1.9.0",
    "torch==2.14.0",
    "torchmetrics==1.9.0",
    "torchvision==0.29.0",
    "tqdm==4.70.0",
]
